spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/billisan_p0_p1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:billisan}
    password: ${MYSQL_PASSWORD}
